import { Product } from './supabase';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Darjeeling Gold First Flush',
    slug: 'darjeeling-gold-first-flush',
    description: 'The champagne of teas. Delicate, muscatel, floral — harvested in spring\'s first light.',
    long_description: `The First Flush Darjeeling is harvested from March to April, capturing the very first tender shoots of the season. Our Darjeeling Gold is sourced exclusively from high-altitude gardens above 2000 meters, resulting in an exceptionally light, golden liquor with a characteristic muscatel character and floral aroma. Every sip reveals layers of peach, apricot, and a lingering sweetness that has made Darjeeling the crown jewel of Indian teas.`,
    price: 899,
    stock: 45,
    image_url: '/darjeeling-gold.png',
    category: 'Black Tea',
    origin: 'Darjeeling, West Bengal',
    weight_options: ['50g', '100g', '250g'],
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Silver Needle White Tea',
    slug: 'silver-needle-white-tea',
    description: 'Rare, revered, and utterly pristine. Only the youngest buds, hand-plucked at dawn.',
    long_description: `Silver Needle is the most prized of all white teas. Our version is crafted from the topmost, silvery buds plucked in the early morning, before the sun can diminish their precious oils and antioxidants. The liquor is a pale golden hue with a sweet, honey-like fragrance that is both delicate and complex. With one of the highest concentrations of natural antioxidants of any tea, Silver Needle is as good for the soul as it is for the body.`,
    price: 1299,
    stock: 28,
    image_url: '/silver-needle.png',
    category: 'White Tea',
    origin: 'Nilgiri, Tamil Nadu',
    weight_options: ['25g', '50g', '100g'],
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Assam Morning Strength',
    slug: 'assam-morning-strength',
    description: 'Bold, malty, full-bodied. The classic breakfast tea that wakes the world.',
    long_description: `Grown in the lush Brahmaputra valley, our Assam Morning Strength is a testament to the power and richness of Assam teas. The deep, coppery red liquor is robust and brisk, with a characteristic malty sweetness that stands up beautifully to milk. Sourced from premium gardens in upper Assam, each batch is carefully selected for its uniform, wiry leaves that unfurl to reveal a bold, invigorating brew.`,
    price: 599,
    stock: 80,
    image_url: '/assam-breakfast.png',
    category: 'Black Tea',
    origin: 'Assam, Northeast India',
    weight_options: ['100g', '250g', '500g'],
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Jasmine Pearl Green',
    slug: 'jasmine-pearl-green',
    description: 'Hand-rolled green pearls scented with fresh jasmine blossoms. Pure poetry.',
    long_description: `Our Jasmine Pearl Green tea is a masterpiece of the tea-maker's art. Premium green tea leaves from the misty hills of Nilgiris are hand-rolled into tiny pearls, then layered with fresh jasmine blossoms multiple times over several nights. Each brewing reveals the jasmine's intoxicating floral fragrance that perfectly complements the tea's natural sweetness and grassy freshness.`,
    price: 749,
    stock: 55,
    image_url: '/green-jasmine.png',
    category: 'Green Tea',
    origin: 'Nilgiri, Tamil Nadu',
    weight_options: ['50g', '100g', '250g'],
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Kashmiri Kahwa Blend',
    slug: 'kashmiri-kahwa-blend',
    description: 'An ancient recipe from the valleys of Kashmir — green tea, saffron, and spice.',
    long_description: `Inspired by the centuries-old traditions of Kashmir, our Kahwa blend combines the finest green tea with hand-picked saffron threads, cardamom, cinnamon, and rose petals. This warming, aromatic blend has been enjoyed in Kashmiri households for generations and is believed to aid digestion, boost immunity, and warm the soul on cold winter nights.`,
    price: 1099,
    stock: 35,
    image_url: '/darjeeling-gold.png',
    category: 'Herbal & Blends',
    origin: 'Kashmir Valley',
    weight_options: ['50g', '100g'],
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Darjeeling Moonlight Oolong',
    slug: 'darjeeling-moonlight-oolong',
    description: 'A rare second flush oolong — the perfect bridge between black and green.',
    long_description: `Our Darjeeling Moonlight Oolong occupies the magical space between green and black tea. Partially oxidized to around 30-40%, this oolong from the high-altitude gardens of Darjeeling delivers a complex, multi-layered experience — the freshness of green tea, the depth of black tea, and a unique honeyed, muscatel sweetness all in one cup.`,
    price: 1150,
    stock: 22,
    image_url: '/silver-needle.png',
    category: 'Oolong Tea',
    origin: 'Darjeeling, West Bengal',
    weight_options: ['50g', '100g'],
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Wellness Tulsi Ginger',
    slug: 'wellness-tulsi-ginger',
    description: 'The ancient Indian remedy — holy basil and ginger for immunity and calm.',
    long_description: `Rooted in Ayurvedic wisdom, our Tulsi Ginger blend harnesses the power of Holy Basil (Tulsi) — revered for centuries as the 'Queen of Herbs' — combined with warming, zesty ginger root. This caffeine-free blend is perfect for calming the mind, boosting immunity, and soothing the digestive system.`,
    price: 499,
    stock: 70,
    image_url: '/green-jasmine.png',
    category: 'Herbal & Blends',
    origin: 'Maharashtra & Kerala',
    weight_options: ['50g', '100g', '200g'],
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Premium Matcha Ceremonial',
    slug: 'premium-matcha-ceremonial',
    description: 'Ceremonial-grade matcha, stone-ground with tradition. Vibrant, umami-rich, sublime.',
    long_description: `Our Ceremonial Grade Matcha is made from the youngest, shade-grown tea leaves that are carefully stone-ground into an ultra-fine powder. The vivid green color indicates its exceptional quality, while the flavor is rich, smooth, and umami-forward with a natural sweetness — a far cry from the bitter matcha found in commercial blends.`,
    price: 1599,
    stock: 18,
    image_url: '/assam-breakfast.png',
    category: 'Green Tea',
    origin: 'Nilgiri, Tamil Nadu',
    weight_options: ['30g', '50g'],
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Teas', icon: '🍵' },
  { id: 'Black Tea', label: 'Black Tea', icon: '🫖' },
  { id: 'Green Tea', label: 'Green Tea', icon: '🌿' },
  { id: 'White Tea', label: 'White Tea', icon: '☁️' },
  { id: 'Oolong Tea', label: 'Oolong Tea', icon: '🌸' },
  { id: 'Herbal & Blends', label: 'Herbal & Blends', icon: '🌼' },
];

export const ADMIN_EMAIL = 'admin@mukherjeetea.com';
